### PR TITLE
Hacktoberfest

### PR DESCRIPTION
**Pull request by dduportal**
Hello Victor,

Please find in this PR the current state of my work :)

I'll try to do more later. Currently it loops over the examples and generate tests reports, after validating the presence of README and config.yaml (check the `demos/.commons/commons.bat`).

Next step is to switch the work you did for building the docker image into the commented tests.

WDYT?

### CODE REVIEW

**Comment by v1v** [comment]
Awesome! I like how it looks like!

Minor question: what do you think of changing the Jenkinsfile to include the call to the  script? Then, if we merge this PR the other one will automatically trigger the automation and we can also work in parallel to enable the TAPS plugin in the jenkins-infra project. WDYT?

**Comment by dduportal** [comment]
Hey @v1v ! That's a good point: let's enable this quality test as soon as possible and then iterate with other PRs.

Let's only take care of the exit code: we might not want to break the build right now: only reporting test failure in the `Jenkinsfile` with something ala `sh "bash ./demos/run.bash || echo "=== They are test failures"` WDYT?

**Comment by v1v** [comment]
@dduportal , it sounds a good approach to let us iterate faster and get some feedback! Poke me if you wanna do it or if i should do it within this PR then I'll merge it straight away.  Thanks

**Comment by v1v** [comment]
I merge this PR  then we can iterate with other PRs

**Pull request merged**
